### ISSUE TITLE
Artifact Hub Release

### ISSUE THREAD

**Issue by JuanPabloSGU** [google/osdfir-infrastructure#22]
### Name and Version

charts/timesketch 0.1.0

### What is the problem this feature will solve?

The issue that I would like to be solved is the current flow of deployment of the chart. At the moment it seems that to use `value.yaml` files the chart requires it to be `pull` and `untar`. As well it seems that for the first time deploying timesketch you would also need to build the dependency charts that associated with the helm chart.

### What is the feature you are proposing to solve the problem?

My recommendation is to publish the chart to [Artifact Hub](https://artifacthub.io/) to allow users to not have to pull down the chart locally on their machines to use `value.yaml` files. In my current setup I am unable to use this helm chart as effectively since I am using [Argocd](https://argoproj.github.io/cd/) to automate all of my deployments within different environments. It introduces needing to upgrade helm versions to support oci compatibility see [here](https://helm.sh/docs/topics/registries/).

### What alternatives have you considered?

I understand that Google may have issues with this implementation that are unknown to myself, let me know if there is a reason why this decision can not be made. Thank you.

**Comment by wajihyassine** [comment]
Hi Juan, thanks for filing! We do want to get these Helm charts up on Artifact Hub as it'll make it easier for others to search and install our charts, it's more been a timing issue due to other priorities and getting the project spun up / working out any remaining kinks then plan on doing an official release on ArtifactHub in the soon future.

I'll assign this to myself to see it through, in the meantime, you should be able to repull the timesketch helm chart without having to run `helm dependency build` but please let me know if you're still running into this.

**Comment by wajihyassine** [comment]
Considering this complete with all Helm charts on ArtifactHub: https://artifacthub.io/packages/search?ts_query_web=osdfir-infra&sort=relevance&page=1
